# Generated by Django 4.2.5 on 2023-10-02 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_remove_director_born'),
    ]

    operations = [
        migrations.AddField(
            model_name='kino',
            name='img',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
